package com.acc.datos.hybernate_project.pojos;
// Generated 1 dic 2025, 8:28:55 by Hibernate Tools 6.6.33.Final


import jakarta.persistence.*;

import java.sql.Date;

/**
 * ProyectoSede generated by hbm2java
 */
@Entity
@Table(name="proyecto_sede"
    ,catalog="proyecto_orm"
)
public class ProyectoSede  implements java.io.Serializable {


     private ProyectoSedeId id;
     private Sede sede;
     private Proyecto proyecto;
     private Date FInicio;
     private Date FFin;

    public ProyectoSede() {
    }

	
    public ProyectoSede(ProyectoSedeId id, Sede sede, Proyecto proyecto, Date FInicio) {
        this.id = id;
        this.sede = sede;
        this.proyecto = proyecto;
        this.FInicio = FInicio;
    }
    public ProyectoSede(ProyectoSedeId id, Sede sede, Proyecto proyecto, Date FInicio, Date FFin) {
       this.id = id;
       this.sede = sede;
       this.proyecto = proyecto;
       this.FInicio = FInicio;
       this.FFin = FFin;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idProy", column=@Column(name="id_proy", nullable=false) ), 
        @AttributeOverride(name="idSede", column=@Column(name="id_sede", nullable=false) ) } )
    public ProyectoSedeId getId() {
        return this.id;
    }
    
    public void setId(ProyectoSedeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede", nullable=false, insertable=false, updatable=false)
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proy", nullable=false, insertable=false, updatable=false)
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="f_inicio", nullable=false, length=10)
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="f_fin", length=10)
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }




}


